version: "3"
services:
  customer-data-container:
    image: spring-data-jpa-hibernate-demo1
    ports:
      - "8086:8086"
    networks:
      - customer-mysql
    depends_on:
      - mysql-standalone
  mysql-standalone:
    image: mysql:8
    networks:
      - customer-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=silviu1234
      - MYSQL_DATABASE=test1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=silviu1357
networks:
  customer-mysql:
    external: true